language: node_js
addons:
  apt:
    packages:
    - sshpass
node_js:
- 8
branchs:
  only:
  - master
script:
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp  -o stricthostkeychecking=no -r config root@47.98.240.154:/var/www/html/fancy
env:
  global:
  - secure: oKeDZNtfOj0nrCguMeaJWy8RvvJWbzOPAIoHPjg/SPyIpHlRyreTxj+FyfuTsIeP5Uzz+JAV/VpvC1U0JhxYA2lLbjBIHjKZgLddvlZEPR3NCNU93BB9xLOj6NhPmPKGlGnMQiS9eYXu65mfqCVg5HXR9P6PtODtC8zm3fr8yuxgVNi5lVyt1u13QvDgFZrZTsBVVzx35i5TaVBRBTr/HvPc261dMr9ZBZypmgaZdu03nPP74PqO68u+3oHqMkwaKz0wieKk3H2fas5YH2OERRvS3R4Dqasoj7KojWGAQkmgOKBggweMqQRHOaIFwQZTX+VJwGAquyxVJfiR7K4QKPhW0wgl47g6qP6E7QQruacV4hjqmeVhgHAw6xxt6boIHcFO6Yq2pP66dzmAM3zY0TPx4G0h46cBl1aAP+pH5K1qfzo3sddbVNhX8i/vO2eM6h4mmFw+tR9gQKSSpwJIJnX5imJXGZpKrGupFlX0mc6unghc0e3i8cssWXkf4Hj0mr4AdpTvfYW5aBiaFmqOCCkWH2/qf5NrzJSS29f2TO90oTChsyoYSU4vrnH2UedWsI6ZFydebksEyrBX3olkySexfp1FMrCxAxgh/21d+COA7Y1vvU8SL84Vm81+mN6jF9Pr6hNmaVq1BrDvyXumWuv2j91BLT0PW3M5DqxTrxw=
  - secure: eKrYl+wWXjA+QiSHYvVfNa9n0bw45EgtOXwB79HrfGYMKhQjJrfB4C+xHcMds8OkBDDEDGH0LjgbWDxruwFQ4+tauDX/eJ1QWea/lvsIlAoP6P7gPUjiibQkmInZd7YY2jqPib42gNc+j4UZ3scxAPxAK0QwRqkBj+a8zGWv7vH+SBKm2jnIi2I05sxDZRgU0C1rDZdl1RC6FDebb/PqcywxuMN6TwOUeIkxAinXkwRGbCWSx7Ww7DMSMNPOPYEQwlbFL3u1NP5kLiCKtTn0j2Qx9iyPHV5W8gILFSu35GAL837e8Iixz2TOKH5qZLbtTsuSGS0lMMZ0Ql41GMWwTNiwr3WjvVm0s9AYNG1g2O7AsZ25l5Feffqvuz9roqElvpycwyAmiHdbER8BeCKhuONikz3eXFBPE6gb5CuUzyheJlbHs6q9jdBOWdphO1d/R6uHIdT6ZAEUo7VYZsfSzDkOmUUu43KqEf83LxflBUCZjY0ISdx7bzIpwiFezruBWaHeUrdPE3WbwWCbnIuMfNHGY2H3zlKsq+EmBXM1xN73cMJMSp8TAirDH45rVjXHCBECiTUwgxo3/t8h8wMKqhDCyDJhCqTyeo1KaI3Ah1KnzRVlDML20Lg/hBdwPFqGSNLPVeQSxGYLumPvpoWkJyVURb8aqopP/pWH4kIcNG8=
