  language: node_js
  addons:
    apt:
      packages:
      - sshpass
  node_js:
    - 8
  branchs:
    only:
    - master  #指定只有检测到master分支有变动时才执行任务
  script:
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e scp  -o stricthostkeychecking=no -r config root@47.98.240.154:/var/www/html/fancy
  env:
    global:
    - secure: ahLPsKXMu2cv1g2Xsk61i+iFR1K7sFznH2+yoCYs66sJAxIQgHmkCvuWboKAVcaoh+pj1+EiFYy6CMLC3rgtOYnYS2A9sHLQta6MZU+y6En1+f4gIp3H04QgYluIcBRgSM8n2QV+t1FAwFbQUm5Ya6n9JKLTm3h+hJuspwUS91vcaK6e5QgeqIOMIExmBNjJvQspravjlagBhKsr3MZN6t3o6DuWam8+obEaKZU/5phEnO/7LWlbbycR5bjJSLbS9tfd1j0Cj+wqzFpwje1PHXgclvY6xURa5qFrOWEWXpfqE16jQhSVighOu1R3GgSU3QE/vtl3SYJ7H7LynRZ87SdlMEAQchYLnpNyWesAU0YZcbHfCovCth/c4NujRbkYaj+xVwR+ZUroMe27tPJAwebCQWSSqUYlV0VHZlHw4tbzl/kxRqNB8alvUUqkSDuYlCYazsu8mqPxTPyvDhw4MhCm1IudOtp/MyRrIQ3/DRgH1oJQqmsfIACYg3Ngj+hiIs5n7nBCEIiiNtMgwNJE7mlmOxY5odBtwb2TnxshJuwHwtodmHdY7xI19/+YZv7QihEqfaqiSr3a16KXlmuFJlN1jHcCbWk+emhgslI1bpBsV/WoGn3b/Uqiy0CRt+Q3OrSRRxTPiAZUxfcBBIf+h4rnOJ2dbC8oqyWVm2wcq9s=
    - secure: T91ci4s07QaGOMTwgu1ZVu8Q8W2keg1j6UB6DNVQBlF5dlRknAdpGcX5nPAfgKeZ2pvrGfHG2regIx/X7v8Xpj7YzO5rfee7penFkryz07KDkJ0Qy5n+Fjq3kNL4ykhlfVZBIbMhCaIFo3S6Oaxql3TwtT0QNaJiA0FHH/1AJJ4qdLhpxAnabW6kegkegkGvtxIWynEGKfCONKJK510KAeuY1PPZ1UCz07nNii7iCDl+Ia6QornKKQTr79h0PwFDy1ZsVqt0VE91Xutn7Qw2HfIuiKRFC0WEDRDJXUuUf40Weczl9FRDlSFVJ5dopfo8lO2zfVf69uaoO2902c0UBL+kOAGOWWuTgKuH9xNR0n8TkaWAQf+IyFfVQkJGam/SCE48lVEili3PgqzGPRCM6M3k5vM3AJrcup0bjO0Oyw0R3JjxDvs14F8ngBGd9jjbAyr47LOqRP/+kDcuOXkm7Tg+8gL3HmH5cU/n+0Zk+qqMYjOVz5lrMACDn2x5Z5ZDIFTJhLf78wWSHZqp5SeouivtKd2VlHPwt+Xk5rSdlsjK78pgWXNbtEcmbYdGWpp/FmauoYEn3XuT2bLEJM/cuqi4nI/t7SzS2ctLBu/6xPHw9ivX6jQ14ccmYgdxxqrQDQc96gQUOvhSi0W1jzpRp/bzcEn5oM19HDb4tdTKZts=
