language: node_js
addons:
  apt:
    packages:
    - sshpass
node_js:
- 8
branchs:
  only:
  - master
script:
- export SSHPASS=$DEPLOY_PASS
- sshpass -e scp  -o stricthostkeychecking=no -r config root@47.98.240.154:/var/www/html/fancy
before_install:
- openssl aes-256-cbc -K $encrypted_87bf11d507f0_key -iv $encrypted_87bf11d507f0_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- echo -e "Host 47.98.240.154\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config