language: node_js
addons:
  apt:
    packages:
    - sshpass
node_js:
  - 8
branchs:
  only:
  - master  #指定只有检测到master分支有变动时才执行任务
script:
  - export SSHPASS=$DEPLOY_PASS
  - npm install cnpm --registry=https://registry.npm.taobao.org
  - cnpm install
  - npm run build
  - sshpass -e scp  -o stricthostkeychecking=no -r dist root@47.98.240.154:/var/www/html/fancy
env:
  global:
  - secure: HMi+aH8NHcTOthSnaVF3mj2Qq9yIMvojM0BmlYpLzh1mE/SM1C+XDaLijVFME+95Q08a7/CNfDNS17tjeb2BEKyShbnGzOZmH7ZtsP5lwwmLXE25X/rskEDAKvyqZWqEaQdZERE1mTvhFpJgtKeju4BUh5X37jMrVNtqLSS0nz6LIxqlcftJJjDCw1o8+GNn2+AHCA32Y1f4MFyr4Q+x+yBiY5+frGPLGXLMskhFLvwnObnKP7vtyPq17vxbKpvfAWBcjQi+WbHpA+fJh3dlDrhNoIv6naM2wBWDMt0QY9OqVLFG3E7VZHJGMD3tYtOEQOHEYDxWjMP1AW2mRYXyT2REw9p63FPTBED+rvD8ESM4V+q/Cymmjv4fMexMa6m5RLGD0YycKlXL7J5p7DG/q78NTdspdRzVp6kzOiWZRW3PU6qUYcO6dB06Ggussl8SyLnbPea/BUHvGZldJ0ecxRcWf8mpT8eyJWtn+HzpIWAxURfPwt1QTSDZFz/dylqJXMzalOkGXLV1jddFEDfPyIzeD0RnP72/vfyBpkgbks5I64doHvWEXd+4Lp2VsKA3GaDxdQJ7ctdO8VuTYubdLOBk/ujLWb3QkCI+Qm2IIJKQtWw+0xbM69Q+k1qmqI9iObwJ4IoP+azmwAZrAYMp/k20iyoAM4s9gPeLZ8XfM/g=
  - secure: Jumd0ogAA24qNP3TBVUgSZ0reyTsLw2zC7UzTsNKROKijdy5VMIfipNrKIKvYB2HqsnxRl/8EnTYVMoZQKkXZM71CslWt4skJbBWRCXdkC7U2MCfzEALWAio4lnUsVX2V0n/DTtwWWkQfHbH09vR4NfQLaTiI24HIN2Rt0SrQjM8jj1xfd1AVn1/HWZPDDl/pHkwWGugukqrTT/TmleEVr23sFTWBUD0CLR5+hmKZ4xWy1J6DDylQkomWSBJr5n0TZLUrcK/2oSmHTMnsIIqLde0WOwqJj+AVPBYnXXkpKsRX+fhbm3AnwnBs6/xFYBcAMuKvnrzm3ukvb4vpsQOE+k8AEfoVPaDUJZtU9LXDy+H6mocCQM0Dp9utGZ4DYxrCXFgBci1ZJCzsw13Q1F20YIA9NMfxrfgm3fxfUoqUe3/PFd8VAy8gb+oRX5QSibUHOW0AYlMTfSybKgO4P8ZYeMsqXBsJdYQmyY1QnD5Veyd2QnAYsKbKbJlYVwHRbWj3tb+Kzq2Th8O7pJj8BWrMTE/ByIPMAnTjMMlz2KTpVqZTJo7149uCfntOVgbxVyzcD7RHDjwbmGDft8zWASiqpjEf2FWmpezSLVvBCxS5aiM6mPTy42SW/Z8lVGdfC8VfHVhwxYEhkQ0xsZRZgA3MqVPxbb3XTZsOLjGJCMkl6E=